// This file was generated by counterfeiter
package fakelockmanager

import (
	"sync"

	"github.com/cloudfoundry-incubator/executor/depot/keyed_lock"
	"github.com/pivotal-golang/lager"
)

type FakeLockManager struct {
	LockStub        func(logger lager.Logger, key string)
	lockMutex       sync.RWMutex
	lockArgsForCall []struct {
		logger lager.Logger
		key    string
	}
	UnlockStub        func(logger lager.Logger, key string)
	unlockMutex       sync.RWMutex
	unlockArgsForCall []struct {
		logger lager.Logger
		key    string
	}
}

func (fake *FakeLockManager) Lock(logger lager.Logger, key string) {
	fake.lockMutex.Lock()
	fake.lockArgsForCall = append(fake.lockArgsForCall, struct {
		logger lager.Logger
		key    string
	}{logger, key})
	fake.lockMutex.Unlock()
	if fake.LockStub != nil {
		fake.LockStub(logger, key)
	}
}

func (fake *FakeLockManager) LockCallCount() int {
	fake.lockMutex.RLock()
	defer fake.lockMutex.RUnlock()
	return len(fake.lockArgsForCall)
}

func (fake *FakeLockManager) LockArgsForCall(i int) (lager.Logger, string) {
	fake.lockMutex.RLock()
	defer fake.lockMutex.RUnlock()
	return fake.lockArgsForCall[i].logger, fake.lockArgsForCall[i].key
}

func (fake *FakeLockManager) Unlock(logger lager.Logger, key string) {
	fake.unlockMutex.Lock()
	fake.unlockArgsForCall = append(fake.unlockArgsForCall, struct {
		logger lager.Logger
		key    string
	}{logger, key})
	fake.unlockMutex.Unlock()
	if fake.UnlockStub != nil {
		fake.UnlockStub(logger, key)
	}
}

func (fake *FakeLockManager) UnlockCallCount() int {
	fake.unlockMutex.RLock()
	defer fake.unlockMutex.RUnlock()
	return len(fake.unlockArgsForCall)
}

func (fake *FakeLockManager) UnlockArgsForCall(i int) (lager.Logger, string) {
	fake.unlockMutex.RLock()
	defer fake.unlockMutex.RUnlock()
	return fake.unlockArgsForCall[i].logger, fake.unlockArgsForCall[i].key
}

var _ keyed_lock.LockManager = new(FakeLockManager)
