// This file was generated by counterfeiter
package fakes

import (
	"github.com/cloudfoundry-incubator/executor/api"
	. "github.com/cloudfoundry-incubator/executor/executor"

	"sync"
)

type FakeClient struct {
	InitializeContainerStub        func(guid string, request api.ContainerInitializationRequest) (api.Container, error)
	initializeContainerMutex       sync.RWMutex
	initializeContainerArgsForCall []struct {
		arg1 string
		arg2 api.ContainerInitializationRequest
	}
	initializeContainerReturns struct {
		result1 api.Container
		result2 error
	}
	RunStub        func(allocationGuid string, request api.ContainerRunRequest) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 string
		arg2 api.ContainerRunRequest
	}
	runReturns struct {
		result1 error
	}
	DeleteContainerStub        func(guid string) error
	deleteContainerMutex       sync.RWMutex
	deleteContainerArgsForCall []struct {
		arg1 string
	}
	deleteContainerReturns struct {
		result1 error
	}
	PingStub        func() error
	pingMutex       sync.RWMutex
	pingArgsForCall []struct{}
	pingReturns struct {
		result1 error
	}
}

func (fake *FakeClient) InitializeContainer(arg1 string, arg2 api.ContainerInitializationRequest) (api.Container, error) {
	fake.initializeContainerMutex.Lock()
	defer fake.initializeContainerMutex.Unlock()
	fake.initializeContainerArgsForCall = append(fake.initializeContainerArgsForCall, struct {
		arg1 string
		arg2 api.ContainerInitializationRequest
	}{arg1, arg2})
	if fake.InitializeContainerStub != nil {
		return fake.InitializeContainerStub(arg1, arg2)
	} else {
		return fake.initializeContainerReturns.result1, fake.initializeContainerReturns.result2
	}
}

func (fake *FakeClient) InitializeContainerCallCount() int {
	fake.initializeContainerMutex.RLock()
	defer fake.initializeContainerMutex.RUnlock()
	return len(fake.initializeContainerArgsForCall)
}

func (fake *FakeClient) InitializeContainerArgsForCall(i int) (string, api.ContainerInitializationRequest) {
	fake.initializeContainerMutex.RLock()
	defer fake.initializeContainerMutex.RUnlock()
	return fake.initializeContainerArgsForCall[i].arg1, fake.initializeContainerArgsForCall[i].arg2
}

func (fake *FakeClient) InitializeContainerReturns(result1 api.Container, result2 error) {
	fake.initializeContainerReturns = struct {
		result1 api.Container
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) Run(arg1 string, arg2 api.ContainerRunRequest) error {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 string
		arg2 api.ContainerRunRequest
	}{arg1, arg2})
	if fake.RunStub != nil {
		return fake.RunStub(arg1, arg2)
	} else {
		return fake.runReturns.result1
	}
}

func (fake *FakeClient) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeClient) RunArgsForCall(i int) (string, api.ContainerRunRequest) {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.runArgsForCall[i].arg1, fake.runArgsForCall[i].arg2
}

func (fake *FakeClient) RunReturns(result1 error) {
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) DeleteContainer(arg1 string) error {
	fake.deleteContainerMutex.Lock()
	defer fake.deleteContainerMutex.Unlock()
	fake.deleteContainerArgsForCall = append(fake.deleteContainerArgsForCall, struct {
		arg1 string
	}{arg1})
	if fake.DeleteContainerStub != nil {
		return fake.DeleteContainerStub(arg1)
	} else {
		return fake.deleteContainerReturns.result1
	}
}

func (fake *FakeClient) DeleteContainerCallCount() int {
	fake.deleteContainerMutex.RLock()
	defer fake.deleteContainerMutex.RUnlock()
	return len(fake.deleteContainerArgsForCall)
}

func (fake *FakeClient) DeleteContainerArgsForCall(i int) string {
	fake.deleteContainerMutex.RLock()
	defer fake.deleteContainerMutex.RUnlock()
	return fake.deleteContainerArgsForCall[i].arg1
}

func (fake *FakeClient) DeleteContainerReturns(result1 error) {
	fake.deleteContainerReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) Ping() error {
	fake.pingMutex.Lock()
	defer fake.pingMutex.Unlock()
	fake.pingArgsForCall = append(fake.pingArgsForCall, struct{}{})
	if fake.PingStub != nil {
		return fake.PingStub()
	} else {
		return fake.pingReturns.result1
	}
}

func (fake *FakeClient) PingCallCount() int {
	fake.pingMutex.RLock()
	defer fake.pingMutex.RUnlock()
	return len(fake.pingArgsForCall)
}

func (fake *FakeClient) PingReturns(result1 error) {
	fake.pingReturns = struct {
		result1 error
	}{result1}
}

var _ Client = new(FakeClient)
