// This file was generated by counterfeiter
package fake_log_streamer

import (
	"io"
	"sync"
)

type FakeLogStreamer struct {
	StdoutStub        func() io.Writer
	stdoutMutex       sync.RWMutex
	stdoutArgsForCall []struct{}
	stdoutReturns     struct {
		result1 io.Writer
	}
	StderrStub        func() io.Writer
	stderrMutex       sync.RWMutex
	stderrArgsForCall []struct{}
	stderrReturns     struct {
		result1 io.Writer
	}
	FlushStub        func()
	flushMutex       sync.RWMutex
	flushArgsForCall []struct{}
}

func (fake *FakeLogStreamer) Stdout() io.Writer {
	fake.stdoutMutex.Lock()
	defer fake.stdoutMutex.Unlock()
	fake.stdoutArgsForCall = append(fake.stdoutArgsForCall, struct{}{})
	if fake.StdoutStub != nil {
		return fake.StdoutStub()
	} else {
		return fake.stdoutReturns.result1
	}
}

func (fake *FakeLogStreamer) StdoutCallCount() int {
	fake.stdoutMutex.RLock()
	defer fake.stdoutMutex.RUnlock()
	return len(fake.stdoutArgsForCall)
}

func (fake *FakeLogStreamer) StdoutReturns(result1 io.Writer) {
	fake.stdoutReturns = struct {
		result1 io.Writer
	}{result1}
}

func (fake *FakeLogStreamer) Stderr() io.Writer {
	fake.stderrMutex.Lock()
	defer fake.stderrMutex.Unlock()
	fake.stderrArgsForCall = append(fake.stderrArgsForCall, struct{}{})
	if fake.StderrStub != nil {
		return fake.StderrStub()
	} else {
		return fake.stderrReturns.result1
	}
}

func (fake *FakeLogStreamer) StderrCallCount() int {
	fake.stderrMutex.RLock()
	defer fake.stderrMutex.RUnlock()
	return len(fake.stderrArgsForCall)
}

func (fake *FakeLogStreamer) StderrReturns(result1 io.Writer) {
	fake.stderrReturns = struct {
		result1 io.Writer
	}{result1}
}

func (fake *FakeLogStreamer) Flush() {
	fake.flushMutex.Lock()
	defer fake.flushMutex.Unlock()
	fake.flushArgsForCall = append(fake.flushArgsForCall, struct{}{})
	if fake.FlushStub != nil {
		fake.FlushStub()
	}
}

func (fake *FakeLogStreamer) FlushCallCount() int {
	fake.flushMutex.RLock()
	defer fake.flushMutex.RUnlock()
	return len(fake.flushArgsForCall)
}
