// This file was generated by counterfeiter
package faketransformer

import (
	"sync"

	"github.com/cloudfoundry-incubator/bbs/models"
	"github.com/cloudfoundry-incubator/executor"
	"github.com/cloudfoundry-incubator/executor/depot/log_streamer"
	"github.com/cloudfoundry-incubator/executor/depot/steps"
	"github.com/cloudfoundry-incubator/executor/depot/transformer"
	"github.com/cloudfoundry-incubator/garden"
	"github.com/pivotal-golang/lager"
)

type FakeTransformer struct {
	StepForStub        func(log_streamer.LogStreamer, *models.Action, garden.Container, string, []executor.PortMapping, lager.Logger) steps.Step
	stepForMutex       sync.RWMutex
	stepForArgsForCall []struct {
		arg1 log_streamer.LogStreamer
		arg2 *models.Action
		arg3 garden.Container
		arg4 string
		arg5 []executor.PortMapping
		arg6 lager.Logger
	}
	stepForReturns struct {
		result1 steps.Step
	}
	StepsForContainerStub        func(lager.Logger, executor.Container, log_streamer.LogStreamer) (steps.Step, <-chan struct{}, error)
	stepsForContainerMutex       sync.RWMutex
	stepsForContainerArgsForCall []struct {
		arg1 lager.Logger
		arg2 executor.Container
		arg3 log_streamer.LogStreamer
	}
	stepsForContainerReturns struct {
		result1 steps.Step
		result2 <-chan struct{}
		result3 error
	}
}

func (fake *FakeTransformer) StepFor(arg1 log_streamer.LogStreamer, arg2 *models.Action, arg3 garden.Container, arg4 string, arg5 []executor.PortMapping, arg6 lager.Logger) steps.Step {
	fake.stepForMutex.Lock()
	fake.stepForArgsForCall = append(fake.stepForArgsForCall, struct {
		arg1 log_streamer.LogStreamer
		arg2 *models.Action
		arg3 garden.Container
		arg4 string
		arg5 []executor.PortMapping
		arg6 lager.Logger
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.stepForMutex.Unlock()
	if fake.StepForStub != nil {
		return fake.StepForStub(arg1, arg2, arg3, arg4, arg5, arg6)
	} else {
		return fake.stepForReturns.result1
	}
}

func (fake *FakeTransformer) StepForCallCount() int {
	fake.stepForMutex.RLock()
	defer fake.stepForMutex.RUnlock()
	return len(fake.stepForArgsForCall)
}

func (fake *FakeTransformer) StepForArgsForCall(i int) (log_streamer.LogStreamer, *models.Action, garden.Container, string, []executor.PortMapping, lager.Logger) {
	fake.stepForMutex.RLock()
	defer fake.stepForMutex.RUnlock()
	return fake.stepForArgsForCall[i].arg1, fake.stepForArgsForCall[i].arg2, fake.stepForArgsForCall[i].arg3, fake.stepForArgsForCall[i].arg4, fake.stepForArgsForCall[i].arg5, fake.stepForArgsForCall[i].arg6
}

func (fake *FakeTransformer) StepForReturns(result1 steps.Step) {
	fake.StepForStub = nil
	fake.stepForReturns = struct {
		result1 steps.Step
	}{result1}
}

func (fake *FakeTransformer) StepsForContainer(arg1 lager.Logger, arg2 executor.Container, arg3 log_streamer.LogStreamer) (steps.Step, <-chan struct{}, error) {
	fake.stepsForContainerMutex.Lock()
	fake.stepsForContainerArgsForCall = append(fake.stepsForContainerArgsForCall, struct {
		arg1 lager.Logger
		arg2 executor.Container
		arg3 log_streamer.LogStreamer
	}{arg1, arg2, arg3})
	fake.stepsForContainerMutex.Unlock()
	if fake.StepsForContainerStub != nil {
		return fake.StepsForContainerStub(arg1, arg2, arg3)
	} else {
		return fake.stepsForContainerReturns.result1, fake.stepsForContainerReturns.result2, fake.stepsForContainerReturns.result3
	}
}

func (fake *FakeTransformer) StepsForContainerCallCount() int {
	fake.stepsForContainerMutex.RLock()
	defer fake.stepsForContainerMutex.RUnlock()
	return len(fake.stepsForContainerArgsForCall)
}

func (fake *FakeTransformer) StepsForContainerArgsForCall(i int) (lager.Logger, executor.Container, log_streamer.LogStreamer) {
	fake.stepsForContainerMutex.RLock()
	defer fake.stepsForContainerMutex.RUnlock()
	return fake.stepsForContainerArgsForCall[i].arg1, fake.stepsForContainerArgsForCall[i].arg2, fake.stepsForContainerArgsForCall[i].arg3
}

func (fake *FakeTransformer) StepsForContainerReturns(result1 steps.Step, result2 <-chan struct{}, result3 error) {
	fake.StepsForContainerStub = nil
	fake.stepsForContainerReturns = struct {
		result1 steps.Step
		result2 <-chan struct{}
		result3 error
	}{result1, result2, result3}
}

var _ transformer.Transformer = new(FakeTransformer)
