// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/executor"
	"github.com/cloudfoundry-incubator/executor/depot/allocationstore"
)

type FakeEventEmitter struct {
	EmitStub        func(executor.Event)
	emitMutex       sync.RWMutex
	emitArgsForCall []struct {
		arg1 executor.Event
	}
}

func (fake *FakeEventEmitter) Emit(arg1 executor.Event) {
	fake.emitMutex.Lock()
	fake.emitArgsForCall = append(fake.emitArgsForCall, struct {
		arg1 executor.Event
	}{arg1})
	fake.emitMutex.Unlock()
	if fake.EmitStub != nil {
		fake.EmitStub(arg1)
	}
}

func (fake *FakeEventEmitter) EmitCallCount() int {
	fake.emitMutex.RLock()
	defer fake.emitMutex.RUnlock()
	return len(fake.emitArgsForCall)
}

func (fake *FakeEventEmitter) EmitArgsForCall(i int) executor.Event {
	fake.emitMutex.RLock()
	defer fake.emitMutex.RUnlock()
	return fake.emitArgsForCall[i].arg1
}

var _ allocationstore.EventEmitter = new(FakeEventEmitter)
