// Code generated by counterfeiter. DO NOT EDIT.
package containerstorefakes

import (
	"os"
	"sync"

	"code.cloudfoundry.org/executor/depot/containerstore"
)

type FakeProxyRunner struct {
	RunStub        func(signals <-chan os.Signal, ready chan<- struct{}) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		signals <-chan os.Signal
		ready   chan<- struct{}
	}
	runReturns struct {
		result1 error
	}
	runReturnsOnCall map[int]struct {
		result1 error
	}
	PortStub        func() uint16
	portMutex       sync.RWMutex
	portArgsForCall []struct{}
	portReturns     struct {
		result1 uint16
	}
	portReturnsOnCall map[int]struct {
		result1 uint16
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProxyRunner) Run(signals <-chan os.Signal, ready chan<- struct{}) error {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		signals <-chan os.Signal
		ready   chan<- struct{}
	}{signals, ready})
	fake.recordInvocation("Run", []interface{}{signals, ready})
	fake.runMutex.Unlock()
	if fake.RunStub != nil {
		return fake.RunStub(signals, ready)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.runReturns.result1
}

func (fake *FakeProxyRunner) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeProxyRunner) RunArgsForCall(i int) (<-chan os.Signal, chan<- struct{}) {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.runArgsForCall[i].signals, fake.runArgsForCall[i].ready
}

func (fake *FakeProxyRunner) RunReturns(result1 error) {
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProxyRunner) RunReturnsOnCall(i int, result1 error) {
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProxyRunner) Port() uint16 {
	fake.portMutex.Lock()
	ret, specificReturn := fake.portReturnsOnCall[len(fake.portArgsForCall)]
	fake.portArgsForCall = append(fake.portArgsForCall, struct{}{})
	fake.recordInvocation("Port", []interface{}{})
	fake.portMutex.Unlock()
	if fake.PortStub != nil {
		return fake.PortStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.portReturns.result1
}

func (fake *FakeProxyRunner) PortCallCount() int {
	fake.portMutex.RLock()
	defer fake.portMutex.RUnlock()
	return len(fake.portArgsForCall)
}

func (fake *FakeProxyRunner) PortReturns(result1 uint16) {
	fake.PortStub = nil
	fake.portReturns = struct {
		result1 uint16
	}{result1}
}

func (fake *FakeProxyRunner) PortReturnsOnCall(i int, result1 uint16) {
	fake.PortStub = nil
	if fake.portReturnsOnCall == nil {
		fake.portReturnsOnCall = make(map[int]struct {
			result1 uint16
		})
	}
	fake.portReturnsOnCall[i] = struct {
		result1 uint16
	}{result1}
}

func (fake *FakeProxyRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	fake.portMutex.RLock()
	defer fake.portMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProxyRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ containerstore.ProxyRunner = new(FakeProxyRunner)
