// Code generated by counterfeiter. DO NOT EDIT.
package containerstorefakes

import (
	"sync"

	"code.cloudfoundry.org/executor"
	"code.cloudfoundry.org/executor/depot/containerstore"
	"code.cloudfoundry.org/garden"
	"code.cloudfoundry.org/lager"
)

type FakeProxyManager struct {
	ProxyPortsStub        func(lager.Logger, *executor.Container) ([]executor.ProxyPortMapping, []uint16)
	proxyPortsMutex       sync.RWMutex
	proxyPortsArgsForCall []struct {
		arg1 lager.Logger
		arg2 *executor.Container
	}
	proxyPortsReturns struct {
		result1 []executor.ProxyPortMapping
		result2 []uint16
	}
	proxyPortsReturnsOnCall map[int]struct {
		result1 []executor.ProxyPortMapping
		result2 []uint16
	}
	BindMountsStub        func(lager.Logger, executor.Container) ([]garden.BindMount, error)
	bindMountsMutex       sync.RWMutex
	bindMountsArgsForCall []struct {
		arg1 lager.Logger
		arg2 executor.Container
	}
	bindMountsReturns struct {
		result1 []garden.BindMount
		result2 error
	}
	bindMountsReturnsOnCall map[int]struct {
		result1 []garden.BindMount
		result2 error
	}
	RunnerStub        func(lager.Logger, executor.Container, <-chan struct{}) (containerstore.ProxyRunner, error)
	runnerMutex       sync.RWMutex
	runnerArgsForCall []struct {
		arg1 lager.Logger
		arg2 executor.Container
		arg3 <-chan struct{}
	}
	runnerReturns struct {
		result1 containerstore.ProxyRunner
		result2 error
	}
	runnerReturnsOnCall map[int]struct {
		result1 containerstore.ProxyRunner
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProxyManager) ProxyPorts(arg1 lager.Logger, arg2 *executor.Container) ([]executor.ProxyPortMapping, []uint16) {
	fake.proxyPortsMutex.Lock()
	ret, specificReturn := fake.proxyPortsReturnsOnCall[len(fake.proxyPortsArgsForCall)]
	fake.proxyPortsArgsForCall = append(fake.proxyPortsArgsForCall, struct {
		arg1 lager.Logger
		arg2 *executor.Container
	}{arg1, arg2})
	fake.recordInvocation("ProxyPorts", []interface{}{arg1, arg2})
	fake.proxyPortsMutex.Unlock()
	if fake.ProxyPortsStub != nil {
		return fake.ProxyPortsStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.proxyPortsReturns.result1, fake.proxyPortsReturns.result2
}

func (fake *FakeProxyManager) ProxyPortsCallCount() int {
	fake.proxyPortsMutex.RLock()
	defer fake.proxyPortsMutex.RUnlock()
	return len(fake.proxyPortsArgsForCall)
}

func (fake *FakeProxyManager) ProxyPortsArgsForCall(i int) (lager.Logger, *executor.Container) {
	fake.proxyPortsMutex.RLock()
	defer fake.proxyPortsMutex.RUnlock()
	return fake.proxyPortsArgsForCall[i].arg1, fake.proxyPortsArgsForCall[i].arg2
}

func (fake *FakeProxyManager) ProxyPortsReturns(result1 []executor.ProxyPortMapping, result2 []uint16) {
	fake.ProxyPortsStub = nil
	fake.proxyPortsReturns = struct {
		result1 []executor.ProxyPortMapping
		result2 []uint16
	}{result1, result2}
}

func (fake *FakeProxyManager) ProxyPortsReturnsOnCall(i int, result1 []executor.ProxyPortMapping, result2 []uint16) {
	fake.ProxyPortsStub = nil
	if fake.proxyPortsReturnsOnCall == nil {
		fake.proxyPortsReturnsOnCall = make(map[int]struct {
			result1 []executor.ProxyPortMapping
			result2 []uint16
		})
	}
	fake.proxyPortsReturnsOnCall[i] = struct {
		result1 []executor.ProxyPortMapping
		result2 []uint16
	}{result1, result2}
}

func (fake *FakeProxyManager) BindMounts(arg1 lager.Logger, arg2 executor.Container) ([]garden.BindMount, error) {
	fake.bindMountsMutex.Lock()
	ret, specificReturn := fake.bindMountsReturnsOnCall[len(fake.bindMountsArgsForCall)]
	fake.bindMountsArgsForCall = append(fake.bindMountsArgsForCall, struct {
		arg1 lager.Logger
		arg2 executor.Container
	}{arg1, arg2})
	fake.recordInvocation("BindMounts", []interface{}{arg1, arg2})
	fake.bindMountsMutex.Unlock()
	if fake.BindMountsStub != nil {
		return fake.BindMountsStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.bindMountsReturns.result1, fake.bindMountsReturns.result2
}

func (fake *FakeProxyManager) BindMountsCallCount() int {
	fake.bindMountsMutex.RLock()
	defer fake.bindMountsMutex.RUnlock()
	return len(fake.bindMountsArgsForCall)
}

func (fake *FakeProxyManager) BindMountsArgsForCall(i int) (lager.Logger, executor.Container) {
	fake.bindMountsMutex.RLock()
	defer fake.bindMountsMutex.RUnlock()
	return fake.bindMountsArgsForCall[i].arg1, fake.bindMountsArgsForCall[i].arg2
}

func (fake *FakeProxyManager) BindMountsReturns(result1 []garden.BindMount, result2 error) {
	fake.BindMountsStub = nil
	fake.bindMountsReturns = struct {
		result1 []garden.BindMount
		result2 error
	}{result1, result2}
}

func (fake *FakeProxyManager) BindMountsReturnsOnCall(i int, result1 []garden.BindMount, result2 error) {
	fake.BindMountsStub = nil
	if fake.bindMountsReturnsOnCall == nil {
		fake.bindMountsReturnsOnCall = make(map[int]struct {
			result1 []garden.BindMount
			result2 error
		})
	}
	fake.bindMountsReturnsOnCall[i] = struct {
		result1 []garden.BindMount
		result2 error
	}{result1, result2}
}

func (fake *FakeProxyManager) Runner(arg1 lager.Logger, arg2 executor.Container, arg3 <-chan struct{}) (containerstore.ProxyRunner, error) {
	fake.runnerMutex.Lock()
	ret, specificReturn := fake.runnerReturnsOnCall[len(fake.runnerArgsForCall)]
	fake.runnerArgsForCall = append(fake.runnerArgsForCall, struct {
		arg1 lager.Logger
		arg2 executor.Container
		arg3 <-chan struct{}
	}{arg1, arg2, arg3})
	fake.recordInvocation("Runner", []interface{}{arg1, arg2, arg3})
	fake.runnerMutex.Unlock()
	if fake.RunnerStub != nil {
		return fake.RunnerStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.runnerReturns.result1, fake.runnerReturns.result2
}

func (fake *FakeProxyManager) RunnerCallCount() int {
	fake.runnerMutex.RLock()
	defer fake.runnerMutex.RUnlock()
	return len(fake.runnerArgsForCall)
}

func (fake *FakeProxyManager) RunnerArgsForCall(i int) (lager.Logger, executor.Container, <-chan struct{}) {
	fake.runnerMutex.RLock()
	defer fake.runnerMutex.RUnlock()
	return fake.runnerArgsForCall[i].arg1, fake.runnerArgsForCall[i].arg2, fake.runnerArgsForCall[i].arg3
}

func (fake *FakeProxyManager) RunnerReturns(result1 containerstore.ProxyRunner, result2 error) {
	fake.RunnerStub = nil
	fake.runnerReturns = struct {
		result1 containerstore.ProxyRunner
		result2 error
	}{result1, result2}
}

func (fake *FakeProxyManager) RunnerReturnsOnCall(i int, result1 containerstore.ProxyRunner, result2 error) {
	fake.RunnerStub = nil
	if fake.runnerReturnsOnCall == nil {
		fake.runnerReturnsOnCall = make(map[int]struct {
			result1 containerstore.ProxyRunner
			result2 error
		})
	}
	fake.runnerReturnsOnCall[i] = struct {
		result1 containerstore.ProxyRunner
		result2 error
	}{result1, result2}
}

func (fake *FakeProxyManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.proxyPortsMutex.RLock()
	defer fake.proxyPortsMutex.RUnlock()
	fake.bindMountsMutex.RLock()
	defer fake.bindMountsMutex.RUnlock()
	fake.runnerMutex.RLock()
	defer fake.runnerMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProxyManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ containerstore.ProxyManager = new(FakeProxyManager)
