#!/bin/bash
# vim: set ft=sh

set -e

# TODO remove once warden-linux docker env changes land
export PATH=/root/go/bin:/usr/local/go/bin:$PATH

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd $(dirname $0)/..

export GOPATH=$PWD/Godeps/_workspace:$GOPATH
export PATH=$PWD/Godeps/_workspace/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo
ginkgo -r -p -failOnPending -randomizeAllSpecs -race -trace "$@"
