#!/bin/bash

set -e

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

export GARDEN_TEST_ROOTFS=/opt/warden/rootfs

go install github.com/onsi/ginkgo/ginkgo

pushd $GOPATH/src/github.com/cloudfoundry-incubator/garden-linux
  export GARDEN_BINPATH=$PWD/old/linux_backend/bin
  make
popd

pushd $GOPATH/src/github.com/cloudfoundry-incubator/executor
  ginkgo -r -p -race -cover -skipMeasurements -keepGoing "$@"
popd
